version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - errcheck
    - gosec
  disable:
    - revive   # Enabled but too verbose (91 doc comments) - re-enable when ready to document
    - unparam  # 2 false positives for error returns that may be used in future

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
