version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
  disable:
    - errcheck  # Too many benign defer Close() errors (87 issues)
    - gosec     # G104 duplicates errcheck, G304 acceptable for config loading
    - revive    # Style-focused, not correctness (95 doc comments)
    - unparam   # Unused params are future-proofing for interface compatibility

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
